import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="border-b border-black/10 dark:border-white/10">
          <div className="mx-auto max-w-6xl px-6 py-4 flex items-center justify-between">
            <a href="/" className="text-lg font-semibold text-blue-700">EDB Foundation</a>
            <nav className="hidden md:flex gap-6 text-sm text-[color:var(--foreground)]/80">
              <a href="/programs" className="hover:text-blue-700">Programs</a>
              <a href="/galleries" className="hover:text-blue-700">Galleries</a>
              <a href="/feedback" className="hover:text-blue-700">Feedback</a>
              <a href="/donate" className="hover:text-blue-700">Donate</a>
              <a href="/contact" className="hover:text-blue-700">Contact</a>
            </nav>
            <a href="/login" className="text-sm text-blue-700 hover:underline">Admin</a>
          </div>
        </header>
        <main>{children}</main>
        <footer className="mt-16 border-t border-black/10 dark:border-white/10">
          <div className="mx-auto max-w-6xl px-6 py-8 text-sm text-[color:var(--foreground)]/70">
            © {new Date().getFullYear()} Everyone Deserves Better Foundation
          </div>
        </footer>
      </body>
    </html>
  );
}
